[project]
name = "tiny-market"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[contracts.sip009-nft]
path = "contracts/sip009-nft.clar"

[contracts.tiny-market]
path = "contracts/tiny-market.clar"